// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCount(arg1) {
  return window['go']['main']['App']['AddCount'](arg1);
}

export function Debug() {
  return window['go']['main']['App']['Debug']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
